const siteIlanVerileri = [
  {
    "images": [
      "/images/adapazar-nda-muhte-em-3-1-daire-0-1785933282673-WhatsApp Image 2026-07-24 at 13.03.37.jpeg"
    ],
    "title": "adapazarında muhteşem 3+1 Daire",
    "ilanno": "Ala-10231",
    "durum": "Satılık",
    "fiyat": "2.250.000",
    "mahalle": "Tepekum",
    "image": "/images/adapazar-nda-muhte-em-3-1-daire-0-1785933282673-WhatsApp Image 2026-07-24 at 13.03.37.jpeg",
    "video_url": "",
    "danisman": "",
    "adi": "Yusuf İşçi",
    "telefon": "0 (532) 407 53 38",
    "fotograf": "",
    "brut": "135",
    "net": "125",
    "oda": "3+1",
    "yas": "30 ve üzeri",
    "kat": "4",
    "katsayisi": "4",
    "isitma": "kombi",
    "mutfak": "Kapalı Mutfak",
    "balkon": "Var",
    "asansor": "Var",
    "otopark": "Açık Otopark",
    "esyali": "Evet",
    "kullanimdurumu": "Boş",
    "siteicinde": "Evet",
    "krediyegun": "Evet",
    "tapudurumu": "Kat Mülkiyeti",
    "takas": "Evet",
    "kategori": "daire",
    "dosyaAdi": "adapazar-nda-muhte-em-3-1-daire.md"
  },
  {
    "images": [],
    "title": "sakarya caddesinde satılık 3+1 daire",
    "price": "2250000",
    "emlak_tipi": "Satılık Daire",
    "il": "Sakarya",
    "ilce": "adapazarı",
    "mahalle": "Tepekum",
    "ilan_no": " 1315935016",
    "m2_brut": "130",
    "m2_net": "110",
    "oda_sayisi": "3+1",
    "bina_yasi": "21-30",
    "bulundugu_kat": "4",
    "kat_sayisi": "4",
    "isitma": "doğalgaz kombi",
    "banyo_sayisi": "1",
    "balkon": "Var",
    "opark": "açık otopark",
    "aidat": "250",
    "image": "/images/whatsapp-image-2026-07-24-at-13.03.37-2-.jpeg",
    "kategori": "daire",
    "dosyaAdi": "sakarya-caddesinde-satılık-3-1-daire.md"
  }
];